CREATE TABLE IF NOT EXISTS "user" ("id" text PRIMARY KEY, "name" text NOT NULL, "email" text NOT NULL UNIQUE, "emailVerified" boolean NOT NULL DEFAULT false, "image" text, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "session" ("id" text PRIMARY KEY, "expiresAt" timestamptz NOT NULL, "token" text NOT NULL UNIQUE, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(), "ipAddress" text, "userAgent" text, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS "account" ("id" text PRIMARY KEY, "accountId" text NOT NULL, "providerId" text NOT NULL, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "verification" ("id" text PRIMARY KEY, "identifier" text NOT NULL, "value" text NOT NULL, "expiresAt" timestamptz NOT NULL, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "rateLimit" ("id" text PRIMARY KEY, "key" text NOT NULL UNIQUE, "count" integer NOT NULL, "lastRequest" bigint NOT NULL);
CREATE TABLE IF NOT EXISTS "categories" ("id" serial PRIMARY KEY, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "name" text NOT NULL, "type" text NOT NULL, "color" text NOT NULL DEFAULT 'blue', "icon" text NOT NULL DEFAULT 'wallet', "imagePath" text, "createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "transactions" ("id" serial PRIMARY KEY, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "categoryId" integer REFERENCES "categories"("id") ON DELETE SET NULL, "type" text NOT NULL, "description" text NOT NULL, "amountCents" integer NOT NULL, "date" text NOT NULL, "notes" text, "imagePath" text, "recurring" boolean NOT NULL DEFAULT false, "createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "budgets" ("id" serial PRIMARY KEY, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "categoryId" integer REFERENCES "categories"("id") ON DELETE SET NULL, "name" text NOT NULL, "limitCents" integer NOT NULL, "month" text NOT NULL, "createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "goals" ("id" serial PRIMARY KEY, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "name" text NOT NULL, "targetCents" integer NOT NULL, "currentCents" integer NOT NULL DEFAULT 0, "deadline" text, "createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "holdings" ("id" serial PRIMARY KEY, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "symbol" text NOT NULL, "assetType" text NOT NULL, "quantity" text NOT NULL, "averageCostCents" integer NOT NULL, "applicationDate" text, "createdAt" timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS "categories_user_idx" ON "categories" ("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "categories_user_name_type_idx" ON "categories" ("userId", "name", "type");
CREATE INDEX IF NOT EXISTS "transactions_user_date_idx" ON "transactions" ("userId", "date");
CREATE INDEX IF NOT EXISTS "transactions_category_idx" ON "transactions" ("categoryId");
CREATE INDEX IF NOT EXISTS "budgets_user_month_idx" ON "budgets" ("userId", "month");
CREATE INDEX IF NOT EXISTS "goals_user_idx" ON "goals" ("userId");
CREATE INDEX IF NOT EXISTS "holdings_user_idx" ON "holdings" ("userId");
CREATE INDEX IF NOT EXISTS "session_user_idx" ON "session" ("userId");
CREATE INDEX IF NOT EXISTS "account_user_idx" ON "account" ("userId");
CREATE INDEX IF NOT EXISTS "budgets_category_idx" ON "budgets" ("categoryId");
INSERT INTO storage.buckets (id, name, public) VALUES ('finance-uploads', 'finance-uploads', false) ON CONFLICT (id) DO UPDATE SET public = false;
