'use client'

import { CalendarDays, Check, PiggyBank, Target, UsersRound } from 'lucide-react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'

type Goal={id:number;name:string;targetCents:number;currentCents:number;deadline:string|null}
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(cents/100)

export function GoalsFeatureCard({goals}:{goals:Goal[]}){
 const featured=[...goals].sort((a,b)=>{const ap=a.targetCents?a.currentCents/a.targetCents:0;const bp=b.targetCents?b.currentCents/b.targetCents:0;return bp-ap}).slice(0,2)
 return <Card size="sm" className="feature-savings-card relative h-full overflow-hidden border-cyan-400/10 bg-gradient-to-br from-card via-card to-blue-500/[.045]"><span className="pointer-events-none absolute -right-20 -top-24 size-64 rounded-full bg-cyan-400/[.08] blur-3xl"/><span className="pointer-events-none absolute -bottom-28 left-1/3 size-60 rounded-full bg-violet-500/[.06] blur-3xl"/><CardHeader className="relative"><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><PiggyBank className="size-4 text-cyan-400"/>Seus planos de economia</CardTitle><CardDescription className="mt-0.5 text-xs">Metas em destaque e evolução dos valores acumulados.</CardDescription></div><span className="hidden rounded-full border border-cyan-400/20 bg-cyan-400/[.07] px-2.5 py-1 text-[10px] text-cyan-400 sm:block">{goals.length} {goals.length===1?'meta':'metas'}</span></div></CardHeader><CardContent className="relative">{featured.length?<div className="grid gap-2.5">{featured.map((goal,index)=><GoalFeatureItem key={goal.id} goal={goal} index={index}/>)}</div>:<div className="flex min-h-28 items-center justify-center rounded-2xl border border-dashed bg-muted/10 text-center"><div><Target className="mx-auto mb-2 size-6 text-cyan-400"/><p className="text-sm font-medium">Nenhum plano criado</p><p className="mt-1 text-xs text-muted-foreground">Adicione uma meta na aba Planejamento.</p></div></div>}</CardContent></Card>
}

function GoalFeatureItem({goal,index}:{goal:Goal;index:number}){const value=Math.min(100,Math.round(goal.currentCents/goal.targetCents*100));const deadline=goal.deadline?new Date(`${goal.deadline}T12:00:00`).toLocaleDateString('pt-BR'):null;return <div className="feature-savings-item group relative overflow-hidden rounded-xl border border-white/[.08] bg-background/55 p-3 backdrop-blur transition-all duration-300 hover:-translate-y-1 hover:border-cyan-400/25 hover:bg-cyan-400/[.035]" style={{animationDelay:`${index*110}ms`}}><div className="flex items-start justify-between gap-3"><span className="flex size-8 items-center justify-center rounded-lg border border-cyan-400/15 bg-cyan-400/[.08] text-cyan-400"><Target className="size-3.5"/></span>{value>=100?<span className="flex items-center gap-1 rounded-full bg-cyan-400/10 px-2 py-1 text-[10px] text-cyan-400"><Check className="size-3"/>Concluída</span>:deadline&&<span className="flex items-center gap-1 text-[10px] text-muted-foreground"><CalendarDays className="size-3"/>{deadline}</span>}</div><h3 className="mt-2.5 truncate text-sm font-medium" title={goal.name}>{goal.name}</h3><div className="mt-2.5 flex items-end justify-between"><span className="font-mono text-xl font-semibold text-cyan-50">{value}%</span><span className="text-[10px] text-muted-foreground">{money(goal.currentCents)} / {money(goal.targetCents)}</span></div><Progress value={value} className="mt-1.5"/><div className="mt-2.5 flex items-center gap-1.5 border-t pt-2 text-[10px] text-muted-foreground"><UsersRound className="size-3"/>Plano individual</div></div>}
